### ISSUE TITLE
Could not set 'file' on ensure: No such file or directory - v.0.3

### ISSUE THREAD

**Issue by maciejbogucki** [evenup/evenup-auditd#27]
Tue Jan 13 10:53:33 +0100 2015 /Stage[main]/Auditd::Install/Package[audit]/ensure (notice): created
Tue Jan 13 10:53:34 +0100 2015 /Stage[main]/Auditd::Config/File[/etc/audit/auditd.conf]/content (notice): content changed '{md5}e1886162554c18906df2ecd258aa4794' to '{md5}2e7b2f91045d9b25b2e950023c77063e'
Tue Jan 13 10:53:34 +0100 2015 /Stage[main]/Auditd::Config/File[/etc/audit/auditd.conf]/mode (notice): mode changed '0640' to '0440'
Tue Jan 13 10:53:34 +0100 2015 Puppet (err): Could not set 'file' on ensure: No such file or directory - /etc/audit/rules.d/audit.rules20150113-8859-1maytaf.lock at 28:/etc/puppet/modules/auditd/manifests/config.pp
Tue Jan 13 10:53:34 +0100 2015 Puppet (err): Could not set 'file' on ensure: No such file or directory - /etc/audit/rules.d/audit.rules20150113-8859-1maytaf.lock at 28:/etc/puppet/modules/auditd/manifests/config.pp
Wrapped exception:
No such file or directory - /etc/audit/rules.d/audit.rules20150113-8859-1maytaf.lock
Tue Jan 13 10:53:34 +0100 2015 /Stage[main]/Auditd::Config/File[/etc/audit/rules.d/audit.rules]/ensure (err): change from absent to file failed: Could not set 'file' on ensure: No such file or directory - /etc/audit/rules.d/audit.rules20150113-8859-1maytaf.lock at 28:/etc/puppet/modules/auditd/manifests/config.pp
Tue Jan 13 10:53:34 +0100 2015 /Stage[main]/Auditd::Service/Service[auditd] (notice): Dependency File[/etc/audit/rules.d/audit.rules] has failures: true
Tue Jan 13 10:53:34 +0100 2015 /Stage[main]/Auditd::Service/Service[auditd] (warning): Skipping because of failed dependencies
Tue Jan 13 10:53:34 +0100 2015 /Stage[main]/Auditd::Service/Service[auditd] (notice): Triggered 'refresh' from 1 events
Tue Jan 13 10:53:34 +0100 2015 /Stage[main]/Auditd/Anchor[auditd::end] (notice): Dependency File[/etc/audit/rules.d/audit.rules] has failures: true
Tue Jan 13 10:53:34 +0100 2015 /Stage[main]/Auditd/Anchor[auditd::end] (warning): Skipping because of failed dependencies

**Comment by jlambert121** [comment]
This is a pretty vague report, could you provide details on how you've configured audit and puppet and OS version info?

**Comment by maciejbogucki** [comment]
Hello,
    
    This is also strange to me. The problem appered when I upgraded from
    version 0.2 (i think so, but it could be 0.1) to version 0.3. The
    problem in only on "Red Hat Enterprise Linux Server release 6.5" (3
    servers has the same problem) and there in no problem in CentOS
    5,6,7.
    
    class telco::centos::audit {
        # configure audit
        class { 'auditd':
          rules => [
           
      "puppet:///telco/config/auditd/centos/audit.rules.${hostname}",
            "puppet:///telco/config/auditd/centos/audit.rules"
          ],
          config_override => {
            # do not rotate files by auditd, we are using logrotate
            'max_log_file_action' => 'ignore',
            'max_log_file' => 0,
          }
        }
        file { "/etc/logrotate.d/auditd":
              owner => root, group => root, mode => 0644,
              source => [
               
      "puppet:///telco/config/auditd/centos/auditd.logrotate.${hostname}",
                "puppet:///telco/config/auditd/centos/auditd.logrotate"
              ],
              require => [ Package[logrotate], ],
        }
      }
    
    Best Regards
    Maciej Bogucki
    
    On 13.01.2015 11:36, Justin Lambert
      wrote:
    
    
      This is a pretty vague report, could you provide details on how
        you've configured audit and puppet and OS version info?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by jlambert121** [comment]
It looks like I am not correctly comparing versions, could you test #28 and make sure that resolves your issue?

**Comment by maciejbogucki** [comment]
Hello,
    
    Not it works! Thank You very much for the fast fix. All the best to
    You.
    
    Best Regards
    Maciej Bogucki
    
    On 13.01.2015 18:52, Justin Lambert
      wrote:
    
    
      It looks like I am not correctly comparing versions, could you
        test #28 and make sure that resolves your issue?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by jlambert121** [comment]
Great!  I have pushed 0.3.1 to the forge with this fix.
